services:
  - type: web
    name: hokage-anime
    env: node
    buildCommand: npm install && npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CALLBACK_URL
        fromService:
          name: hokage-anime
          type: web
          property: url
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: hokage-data
      mountPath: /data
      sizeGB: 1 